set_standby_brightness:
  name: Set standby brightness
  description: >
    Sets the brightness level for a TP-Link dimmer. If the light is off,
    the standby brightness is updated without turning the light on.
    If the light is already on, the brightness is adjusted normally.
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: light
          integration: tplink

    brightness:
      required: true
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
